-- -- src/main/resources/data.sql 수정
-- INSERT INTO hospital_master (hospital_name, hpid, longitude, latitude)
-- VALUES ('서울대학교병원', 'HP001', 127.0000, 37.5796);
--
-- INSERT INTO hospital_master (hospital_name, hpid, longitude, latitude)
-- VALUES ('세브란스병원', 'HP002', 126.9411, 37.5622);
--
-- INSERT INTO weight_pregnant_configuration (category, delivery_available_weight, obstetric_surgery_weight, nicu_available_weight, delivery_room_available_weight, emergency_room_available_weight, operating_room_threshold, incubator_weight, premature_ventilator_weight, operating_room_bonus_weight, nicu_scale_weight, max_nicu_scale_score)
-- VALUES ('PREGNANT', 40.0, 20.0, 10.0, 30.0, 30.0, 3, 10.0, 5.0, 5.0, 2.0, 10.0);
-- INSERT INTO weight_general_configuration (
--     category,
--     emergency_room_weight,
--     severe_disease_weight,
--     icu_weight,
--     equipment_weight,
--     congestion_weight,
--     ecmo_bonus,
--     crrt_bonus,
--     angio_bonus,
--     created_at,
--     updated_at
-- )
-- VALUES (
--            'GENERAL',
--            40.0,
--            15.0,
--            20.0,
--            10.0,
--            15.0,
--            10.0,
--            5.0,
--            5.0,
--            NOW(),
--            NOW()
--        );
-- INSERT INTO weight_pediatric_configuration (
--     category,
--     pediatric_emergency_weight,
--     pediatric_icu_weight,
--     pediatric_emergency_icu_weight,
--     incubator_weight,
--     preemie_venti_weight,
--     pediatric_venti_weight,
--     negative_isolation_weight,
--     isolation_weight,
--     special_treatment_weight,
--     low_birth_weight_bonus,
--     created_at,
--     updated_at
-- )
-- VALUES (
--            'PEDIATRIC',
--            40.0,
--            20.0,
--            25.0,
--            15.0,
--            15.0,
--            10.0,
--            10.0,
--            5.0,
--            15.0,
--            20.0,
--            NOW(),
--            NOW()
--        );
 SELECT 1;